### ISSUE TITLE
Issue 1.1 - Add Enhancements to Beginners Page. 

### ISSUE THREAD

**Issue by Ashita2000** [Ashita2000/GoogleAnalytics#4]
1. Add Proper Numbering to Google Analytics Setup Steps. 
2. Correct Spellings wherever required. 
3. Add Campaign Tagging step as well.

**Comment by anchal0997** [comment]
I would like to work on this issue.

**Comment by Ashita2000** [comment]
Assigned to you @anchal0997 .

**Comment by Ashita2000** [comment]
Resolved with the PR: https://github.com/Ashita2000/GoogleAnalytics/pull/5
